source 'https://rubygems.org'
 
gem 'jekyll'
gem 'github-pages'
gem 'bourbon'

gem 'octopress', '~> 3.0.11'
gem 'octopress-image-tag'
gem 'octopress-hooks'
gem 'octopress-paginate'
gem 'octopress-codeblock'
gem 'octopress-quote-tag'
gem 'octopress-codefence'
gem 'octopress-solarized'
gem 'octopress-gist'
gem 'octopress-deploy'
